### PR TITLE
Report the number of tests in result

### PR DESCRIPTION
**Pull request by jakebolewski**
``` julia
julia> include("runtests.jl")
Test Summary:
outer    |  Pass: 8/8 (100.0 %)
  inner1 |  Pass: 4/4 (100.0 %)
    d    |  Pass: 1/1 (100.0 %)
  inner1 |  Pass: 4/4 (100.0 %)
```

### CODE REVIEW

**Comment by simonbyrne** [comment]
You could even get rid of `Pass:`, or make it a heading?

**Comment by simonbyrne** [comment]
I should expand: what I was thinking was simply display the proportion of passing tests (even when there are test fails, as the proportion of failing is just redundant information). I also agree with Jake that you don't need percentages. So I was thinking something like:

```
Test set | Passing
==================
outer    |  8 / 8
  inner1 |  4 / 4
    d    |  1 / 1
  inner1 |  4 / 4
```

You also want some way for the reader to quickly identify which sets have failed. I guess some sort of colour?

**Comment by simonbyrne** [comment]
or even a bar graph using [block elements](https://en.wikipedia.org/wiki/Block_Elements)?

**Comment by jakebolewski** [comment]
that seems even more useless than printing the % :-)

**Comment by simonbyrne** [comment]
Yeah, I'm not convinced it would be a good idea, but visually it should be quicker to scan through than looking at percentages.

**Comment by IainNZ** [comment]
Headings get tricky if you have, e.g. 0 passing tests, you have to walk the whole tree to get totals first, and so on. I'll think on it

**Comment by simonbyrne** [comment]
I meant have the heading be always `Passing`. So if all tests failed you would have

```
Test set | Passing
==================
outer    |  0 / 8
  inner1 |  0 / 4
    d    |  0 / 1
  inner1 |  0 / 4
```

**Comment by IainNZ** [comment]
Oh I see what you're saying. Interesting. I'll explore.
I'm not going to merge this, but I'll incorporate the original suggetsion, just without the %

**Pull request closed without merging**
