### PR TITLE
use correct 0.5 dev version in README

### PR DESCRIPTION
**Pull request by stevengj**
You should check for the version where https://github.com/JuliaLang/julia/pull/13062 was merged.

### CODE REVIEW

**Comment by IainNZ** [comment]
Why?

**Comment by stevengj** [comment]
Because the code is not correct for all `0.5-dev` versions?  Of course, as a practical matter, not many people are likely to use a version where the difference matters.  It's more the general principle that `VERSION >= v"X.Y-"` checks should be viewed as automatically suspect.

**Comment by tkelman** [comment]
Bump. I'm going to merge this. Helps if this code ever needs to be used in bisecting something. @stevengj want an invite to the JuliaCI org?

**Comment by stevengj** [comment]
Sure.

**Pull request merged**
