### PR TITLE
prints green dots as tests run to indicate progress

### PR DESCRIPTION
**Pull request by ssfrr**

### CODE REVIEW

**Comment by ssfrr** [comment]
Just a little thing I'm trying out:

anim

**Comment by IainNZ** [comment]
Hah cute. Yet another option that could be added! Or even better, a way to have fancier test sets that people can customize to their hearts contents + share.

**Comment by jkroso** [comment]
A good way to support this kind of thing would be with an event emitter. This is what I have been using in [jest.jl](//github.com/jkroso/jest.jl). You can have multiple reporters hooked up at the same time which is good if you want to generate [TAP](https://testanything.org) output as well as render to the console. Which some CI tools probably would actually want to do.

Also I think that by default it should only return test results not print them also. Because in general I prefer to run my tests interactively or embed them alongside the code they test. If they print output by default then I wouldn't be able to do the later.

**Comment by IainNZ** [comment]
Hi @jkroso, those are some interesting thoughts. Could you please write them as an issue on JuliaLang/julia? After this was merged in Base, this exists only to mirror Base for Julia 0.4 users, so your insight will get lost here.

**Pull request closed without merging**
